/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Ekrany;

import java.awt.*;
import javax.swing.JOptionPane;

/**
 *
 * @author huawei
 */
public class Arkusz_Reklamacyjny extends javax.swing.JFrame {

    /**
     * Creates new form Arkusz_Reklamacyjny
     */
    public Arkusz_Reklamacyjny() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        potwierdzButton = new javax.swing.JButton();
        odrzucButton = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        potwierdzButton.setText("Potwierdź");
        potwierdzButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                potwierdzButtonActionPerformed(evt);
            }
        });
        getContentPane().add(potwierdzButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 210, 200, 70));

        odrzucButton.setText("Odrzuć");
        odrzucButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                odrzucButtonActionPerformed(evt);
            }
        });
        getContentPane().add(odrzucButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 210, 200, 70));

        jTextField1.setText("Treść Reklamacji");
        jTextField1.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 400, 209));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void potwierdzButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_potwierdzButtonActionPerformed
        
        JOptionPane.showMessageDialog(new Frame(), "Reklamacja zlozona", "Uwaga", JOptionPane.PLAIN_MESSAGE);
        this.setVisible(false);
    }//GEN-LAST:event_potwierdzButtonActionPerformed

    private void odrzucButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_odrzucButtonActionPerformed
        
        
        this.setVisible(false);
    }//GEN-LAST:event_odrzucButtonActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Arkusz_Reklamacyjny.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Arkusz_Reklamacyjny.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Arkusz_Reklamacyjny.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Arkusz_Reklamacyjny.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Arkusz_Reklamacyjny().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField jTextField1;
    private javax.swing.JButton odrzucButton;
    private javax.swing.JButton potwierdzButton;
    // End of variables declaration//GEN-END:variables
}
