/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Ekrany;

/**
 *
 * @author Maciek
 */
public class Ekran_projektu_klienta extends javax.swing.JFrame {

    /**
     * Creates new form Ekran_projektu_klienta
     */
    public Ekran_projektu_klienta() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        tarcicaBox = new javax.swing.JComboBox<>();
        typMeblaBox = new javax.swing.JComboBox<>();
        tkaninaObiciowaBox = new javax.swing.JComboBox<>();
        jTextField1 = new javax.swing.JTextField();
        okleinaBox = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        plytaMeblowaBox = new javax.swing.JComboBox<>();
        jButton3 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jComboBox6 = new javax.swing.JComboBox<>();
        piankaTapicerskaBox = new javax.swing.JComboBox<>();
        jLabel11 = new javax.swing.JLabel();
        wymiaryGabarytowe = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel13 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jComboBox8 = new javax.swing.JComboBox<>();
        jLabel15 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jTextField5 = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
<<<<<<< HEAD
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
=======
        powrotButton = new javax.swing.JButton();
>>>>>>> c0d0875bf74ddee410a54eb4b875a804f6c54853

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setText("Dodawanie półproduktów");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 590, 350, 50));
        jPanel2.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 640, 540, 10));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setText("Tarcica");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 310, 150, 40));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel3.setText("Typ");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 70, 180, 40));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel4.setText("Materiały:");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 170, 180, 30));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel5.setText("Tkanina obiciowa");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 210, 150, 40));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel6.setText("Płyta meblowa");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 260, 150, 40));

        tarcicaBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Deska dębowa", "Drewno bukowe", "Drewno sosnowe", "Drewno brzozowe", "Drewno hebanowe" }));
        jPanel2.add(tarcicaBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 310, 220, 40));

        typMeblaBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " ", "Stol", "Krzeslo", "Fotel", "Lozko", "Sofa", "Biurko", "Szafa", "Komoda", "Szafka nocna", "Naroznik", "Regal", "Kredens" }));
        typMeblaBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                typMeblaBoxActionPerformed(evt);
            }
        });
        jPanel2.add(typMeblaBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 70, 220, 40));

        tkaninaObiciowaBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Flok", "Welwet", "Ekoskóra", "Szenil" }));
        jPanel2.add(tkaninaObiciowaBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 210, 220, 40));

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        jPanel2.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 850, 150, 40));

        okleinaBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Fornir naturalny", "Fornir modyfikowany", "Okleina PCV" }));
        jPanel2.add(okleinaBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 410, 220, 40));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel7.setText("Okleina");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 410, 150, 40));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel8.setText("Pianka tapicerska");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 360, 150, 40));

        plytaMeblowaBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Płyta wiórowa", "Płyta paździerzowa", "Płyta pilśniowa", "Płyta MDF" }));
        jPanel2.add(plytaMeblowaBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 260, 220, 40));

        jButton3.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jButton3.setText("+");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 510, 50, 40));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel9.setText("Liczba sztuk");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 860, 180, 30));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel10.setText("Łączenia");
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 460, 180, 30));

        jComboBox6.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Wkręty", "Klej", "Wciskowe", "Kołki", "Mimośrody i trzpienie", "Gwintowane" }));
        jPanel2.add(jComboBox6, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 460, 220, 40));

        piankaTapicerskaBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pianka poliuretanowa", "Pianka wysokoelastyczna", "Pianka polieterowa"}));
        jPanel2.add(piankaTapicerskaBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 360, 220, 40));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel11.setText("Wymiary gabarytowe [mm]");
        jPanel2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 120, 210, 40));

        wymiaryGabarytowe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                wymiaryGabarytoweActionPerformed(evt);
            }
        });
        jPanel2.add(wymiaryGabarytowe, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 120, 220, 40));

        jLabel12.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel12.setText("Dodawanie własnego projektu");
        jPanel2.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 350, 50));
        jPanel2.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 540, 10));

        jLabel13.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel13.setText("Nazwa");
        jPanel2.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 650, 180, 40));

        jTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField3ActionPerformed(evt);
            }
        });
        jPanel2.add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 650, 220, 40));

        jTextField4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField4ActionPerformed(evt);
            }
        });
        jPanel2.add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 700, 220, 40));

        jLabel14.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel14.setText("Wymiary gabarytowe");
        jPanel2.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 700, 180, 40));

        jComboBox8.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Stelaż", "Rama", "Front", "Dekory"}));
        jComboBox8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox8ActionPerformed(evt);
            }
        });
        jPanel2.add(jComboBox8, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 750, 220, 40));

        jLabel15.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel15.setText("Rodzaj");
        jPanel2.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 750, 180, 30));

        jButton4.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jButton4.setText("Dodaj projekt");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 950, 270, 40));

        jTextField5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField5ActionPerformed(evt);
            }
        });
        jPanel2.add(jTextField5, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 800, 150, 40));

        jLabel16.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel16.setText("Rysunek");
        jPanel2.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 800, 180, 30));

        jButton5.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jButton5.setText("+");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 800, 50, 40));

        jButton6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButton6.setText("Dodaj półprodukt");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 900, 150, 30));

        jLabel17.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel17.setText("Rysunek");
        jPanel2.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 510, 180, 30));

        jLabel18.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel18.setText("Liczba sztuk");
        jPanel2.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 570, 180, 30));

<<<<<<< HEAD
        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });
        jPanel2.add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 510, 150, 40));

        jTextField6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField6ActionPerformed(evt);
            }
        });
        jPanel2.add(jTextField6, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 560, 150, 40));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 560, 1000));
=======
        powrotButton.setText("Powrot");
        powrotButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                powrotButtonActionPerformed(evt);
            }
        });
        jPanel2.add(powrotButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 10, 110, 40));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 560, 970));
>>>>>>> c0d0875bf74ddee410a54eb4b875a804f6c54853

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 600, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1033, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void wymiaryGabarytoweActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_wymiaryGabarytoweActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_wymiaryGabarytoweActionPerformed

    private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField3ActionPerformed

    private void jTextField4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField4ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jTextField5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField5ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    private void typMeblaBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_typMeblaBoxActionPerformed
        if (evt.getSource()==typMeblaBox){
            if(typMeblaBox.getSelectedItem()=="Stol"){
                tkaninaObiciowaBox.setEnabled(false);
                plytaMeblowaBox.setEnabled(false);
                tarcicaBox.setEnabled(true);
                piankaTapicerskaBox.setEnabled(false);
                okleinaBox.setEnabled(false);
            }else if(typMeblaBox.getSelectedItem()=="Krzeslo"){
                tkaninaObiciowaBox.setEnabled(false);
                plytaMeblowaBox.setEnabled(false);
                tarcicaBox.setEnabled(true);
                piankaTapicerskaBox.setEnabled(false);
                okleinaBox.setEnabled(false);
            }else if(typMeblaBox.getSelectedItem()=="Fotel"){
                tkaninaObiciowaBox.setEnabled(true);
                plytaMeblowaBox.setEnabled(false);
                tarcicaBox.setEnabled(false);
                piankaTapicerskaBox.setEnabled(true);
                okleinaBox.setEnabled(false);
            }else if(typMeblaBox.getSelectedItem()=="Lozko"){
                tkaninaObiciowaBox.setEnabled(false);
                plytaMeblowaBox.setEnabled(false);
                tarcicaBox.setEnabled(true);
                piankaTapicerskaBox.setEnabled(false);
                okleinaBox.setEnabled(false);
            }else if(typMeblaBox.getSelectedItem()=="Sofa"){
                tkaninaObiciowaBox.setEnabled(true);
                plytaMeblowaBox.setEnabled(false);
                tarcicaBox.setEnabled(false);
                piankaTapicerskaBox.setEnabled(true);
                okleinaBox.setEnabled(false);
            }else if(typMeblaBox.getSelectedItem()=="Biurko"){
                tkaninaObiciowaBox.setEnabled(false);
                plytaMeblowaBox.setEnabled(true);
                tarcicaBox.setEnabled(false);
                piankaTapicerskaBox.setEnabled(false);
                okleinaBox.setEnabled(true);
            }else if(typMeblaBox.getSelectedItem()=="Szafa"){
                tkaninaObiciowaBox.setEnabled(false);
                plytaMeblowaBox.setEnabled(true);
                tarcicaBox.setEnabled(false);
                piankaTapicerskaBox.setEnabled(false);
                okleinaBox.setEnabled(true);
            }else if(typMeblaBox.getSelectedItem()=="Komoda"){
                tkaninaObiciowaBox.setEnabled(false);
                plytaMeblowaBox.setEnabled(true);
                tarcicaBox.setEnabled(false);
                piankaTapicerskaBox.setEnabled(false);
                okleinaBox.setEnabled(true);
            }else if(typMeblaBox.getSelectedItem()=="Szafka nocna"){
                tkaninaObiciowaBox.setEnabled(false);
                plytaMeblowaBox.setEnabled(true);
                tarcicaBox.setEnabled(false);
                piankaTapicerskaBox.setEnabled(false);
                okleinaBox.setEnabled(true);
            }else if(typMeblaBox.getSelectedItem()=="Naroznik"){
                tkaninaObiciowaBox.setEnabled(true);
                plytaMeblowaBox.setEnabled(false);
                tarcicaBox.setEnabled(false);
                piankaTapicerskaBox.setEnabled(true);
                okleinaBox.setEnabled(false);
            }else if(typMeblaBox.getSelectedItem()=="Regal"){
                tkaninaObiciowaBox.setEnabled(false);
                plytaMeblowaBox.setEnabled(true);
                tarcicaBox.setEnabled(false);
                piankaTapicerskaBox.setEnabled(false);
                okleinaBox.setEnabled(true);
            }else if(typMeblaBox.getSelectedItem()=="Kredens"){
                tkaninaObiciowaBox.setEnabled(false);
                plytaMeblowaBox.setEnabled(false);
                tarcicaBox.setEnabled(true);
                piankaTapicerskaBox.setEnabled(false);
                okleinaBox.setEnabled(false);
            }
        }
    }//GEN-LAST:event_typMeblaBoxActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton6ActionPerformed

<<<<<<< HEAD
    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void jTextField6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField6ActionPerformed

    private void jComboBox8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox8ActionPerformed
=======
    private void powrotButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_powrotButtonActionPerformed
        new EkranKlienta().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_powrotButtonActionPerformed
>>>>>>> c0d0875bf74ddee410a54eb4b875a804f6c54853

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ekran_projektu_klienta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ekran_projektu_klienta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ekran_projektu_klienta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ekran_projektu_klienta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ekran_projektu_klienta().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JComboBox<String> jComboBox6;
    private javax.swing.JComboBox<String> jComboBox8;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JComboBox<String> okleinaBox;
    private javax.swing.JComboBox<String> piankaTapicerskaBox;
    private javax.swing.JComboBox<String> plytaMeblowaBox;
    private javax.swing.JButton powrotButton;
    private javax.swing.JComboBox<String> tarcicaBox;
    private javax.swing.JComboBox<String> tkaninaObiciowaBox;
    private javax.swing.JComboBox<String> typMeblaBox;
    private javax.swing.JTextField wymiaryGabarytowe;
    // End of variables declaration//GEN-END:variables
}
