/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Ekrany;

import java.sql.ResultSet;
import java.sql.*;  

/**
 *
 * @author Maciek
 */
public class Ekran_rejestracji extends javax.swing.JFrame {

    /**
     * Creates new form Ekran_rejestracji
     */
    public Ekran_rejestracji() {
        initComponents();
    }

    public void clearContent() {
        imie_textF.setText("");
        Nazwisko_textF.setText("");
        email_textF.setText("");
        ulica_textF.setText("");
        login_textF.setText("");
        nr_domu_textF.setText("");
        nr_mieszkania_textF.setText("");
        kod_pocztowy_textF.setText("");
        miaso__textF.setText("");
        nr_telefonu_textF.setText("");
        kraj__textF.setText("");

        password.setText("");
        password1.setText("");
    }



    private boolean sprawdz_login(String login) {
        boolean login_poprawny = false;

        try{  
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3307/firma?serverTimezone=UTC","root","root");   
            Statement stmt = con.createStatement();
            String zapytanie =
                "SELECT Login\n"+
                "FROM (\n"+
                    "SELECT klient.Login\n"+
                    "FROM klient\n"+
                    "UNION\n" +
                    "SELECT pracownik.Login AS Login\n"+
                    "FROM pracownik\n"+
                ") tab\n"+
                "WHERE Login = '"+ login +"' \n";
            ResultSet rs = stmt.executeQuery(zapytanie);
            if(rs.next()) {
                // System.out.println("Uzytkownik o danym loginie już istnieje");
            } else {
                // System.out.println("Login poprawny");
                login_poprawny = true;
            }

            con.close(); 
        } catch(Exception e) { 
            System.out.println(e.getMessage());
        }  
        return login_poprawny;   
    }  

    private boolean sprawdz_email(String email) {
        boolean email_poprawny = false;

        try{  
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3307/firma?serverTimezone=UTC","root","root");   
            Statement stmt = con.createStatement();
            String zapytanie =
                "SELECT klient.Email\n"+
                "FROM klient\n"+
                "WHERE Email = '"+ email +"' \n";
            ResultSet rs = stmt.executeQuery(zapytanie);
            if(rs.next()) {
                // System.out.println("Uzytkownik o danym adresie email już istnieje");
            } else {
                // System.out.println("email poprawny");
                email_poprawny = true;
            }

            con.close(); 
        } catch(Exception e) { 
            System.out.println(e.getMessage());
        }  
        return email_poprawny;   
    }  

    private boolean rejestracja(String imie, String nazwisko, String nr_telefonu, String email, String kraj, 
        String kod_pocztowy, String miejscowosc, String ulica, String nr_domu, String nr_mieszkania, String login, char[] haslo) {
        boolean rejestracja_sie_powiodla = false;

        String haslo_s = new String(haslo);

        try{  
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3307/firma?serverTimezone=UTC","root","root");   
            Statement stmt = con.createStatement();
            String zapytanie =
                        "INSERT INTO klient (Imie, Nazwisko, Numer_telefonu, Email, Adres_Kraj, " +
                        "Adres_AdresPocztowy, Adres_Miejscowosc, Adres_Ulica, Adres_NumerDomu, Adres_NumerMieszkania, Login, Haslo) " +
                        "VALUES ('" + imie + "', '" + nazwisko +"', '" + nr_telefonu + "', '" +
                        email + "', '"  + kraj + "', '" + kod_pocztowy + "', '" + miejscowosc + "', '" + ulica + "', '" + nr_domu + "', '" + nr_mieszkania + "', '" + login + "', '" + haslo_s +"');\n";
            
            stmt.executeUpdate(zapytanie); 
            con.close(); 
        } catch(Exception e) { 
            System.out.println(e.getMessage());
        }  

        return rejestracja_sie_powiodla;
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        kraj__textF = new javax.swing.JTextField();
        imie_textF = new javax.swing.JTextField();
        email_textF = new javax.swing.JTextField();
        login_textF = new javax.swing.JTextField();
        Nazwisko_textF = new javax.swing.JTextField();
        ulica_textF = new javax.swing.JTextField();
        nr_mieszkania_textF = new javax.swing.JTextField();
        kod_pocztowy_textF = new javax.swing.JTextField();
        miaso__textF = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        nr_domu_textF = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        zarejestruj_button = new javax.swing.JButton();
        powrotButton = new javax.swing.JButton();
        nr_telefonu_textF = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        message_label = new javax.swing.JLabel();
        password = new javax.swing.JPasswordField();
        password1 = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setText("Rejestracja");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 160, 50));
        jPanel2.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 470, 20));
        jPanel2.add(kraj__textF, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 460, 220, 40));
        jPanel2.add(imie_textF, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 220, 40));
        jPanel2.add(email_textF, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, 220, 40));
        jPanel2.add(login_textF, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, 220, 40));
        jPanel2.add(Nazwisko_textF, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 110, 220, 40));
        jPanel2.add(ulica_textF, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 180, 220, 40));
        jPanel2.add(nr_mieszkania_textF, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 250, 100, 40));
        jPanel2.add(kod_pocztowy_textF, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 320, 220, 40));
        jPanel2.add(miaso__textF, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 390, 220, 40));

        jLabel2.setText("Powtórz hasło:");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 370, -1, -1));

        jLabel3.setText("Imię:");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, -1, -1));

        jLabel4.setText("E-mail:");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, -1, -1));

        jLabel5.setText("Login:");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, -1, -1));

        jLabel6.setText("Hasło:");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 300, -1, -1));

        jLabel7.setText("Nazwisko:");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 90, -1, -1));

        jLabel8.setText("Ulica:");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 160, -1, -1));

        jLabel9.setText("Nr mieszkania");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 230, -1, -1));

        jLabel10.setText("Kod pocztowy:");
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 300, -1, -1));

        jLabel11.setText("Kraj:");
        jPanel2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 440, -1, -1));

        jLabel12.setText("Miasto:");
        jPanel2.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 370, -1, -1));
        jPanel2.add(nr_domu_textF, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 250, 100, 40));

        jLabel13.setText("Nr domu");
        jPanel2.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 230, -1, -1));

        zarejestruj_button.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        zarejestruj_button.setText("Zarejestruj się");
        zarejestruj_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                zarejestruj_buttonActionPerformed(evt);
            }
        });
        jPanel2.add(zarejestruj_button, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 570, 220, 70));

        powrotButton.setText("Powrót");
        powrotButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                powrotButtonActionPerformed(evt);
            }
        });
        jPanel2.add(powrotButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 10, 100, 40));
        jPanel2.add(nr_telefonu_textF, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 460, 220, 40));

        jLabel14.setText("Numer telefonu:");
        jPanel2.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 440, -1, -1));

        message_label.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        message_label.setForeground(new java.awt.Color(204, 0, 0));
        message_label.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        message_label.setToolTipText("");
        jPanel2.add(message_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 520, 310, 30));
        jPanel2.add(password, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 320, 220, 40));
        jPanel2.add(password1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 390, 220, 40));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 40, 500, 720));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, 800));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void powrotButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_powrotButtonActionPerformed
        new Ekran_glowny().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_powrotButtonActionPerformed

    private void zarejestruj_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_zarejestruj_buttonActionPerformed
        if (imie_textF.getText().equals("") || Nazwisko_textF.getText().equals("") || 
            email_textF.getText().equals("") || ulica_textF.getText().equals("") || 
            login_textF.getText().equals("") || nr_domu_textF.getText().equals("") ||
            password.getPassword().length == 0 || kod_pocztowy_textF.getText().equals("") || 
            password1.getPassword().length == 0 || miaso__textF.getText().equals("") || 
            nr_telefonu_textF.getText().equals("") || kraj__textF.getText().equals("")) {
                message_label.setForeground(new java.awt.Color(204, 0, 0));
                message_label.setText("Wprowadz wszystkie wymagane dane logowania");
        } else {
            String pass1 = new String(password.getPassword());
            String pass2 = new String(password1.getPassword());
            if ((pass2.equals(pass1) == false)) {
                message_label.setForeground(new java.awt.Color(204, 0, 0));
                message_label.setText("Wprowadzone hasła różnią się od siebie");
            } else {
                message_label.setForeground(new java.awt.Color(204, 0, 0));
                message_label.setText("");

                if (sprawdz_login(login_textF.getText())) {
                    if(sprawdz_email(email_textF.getText())){
                        rejestracja(imie_textF.getText(), Nazwisko_textF.getText(), nr_telefonu_textF.getText(), email_textF.getText(), 
                        kraj__textF.getText(), kod_pocztowy_textF.getText(), miaso__textF.getText(), ulica_textF.getText(), 
                        nr_domu_textF.getText(), nr_mieszkania_textF.getText(), login_textF.getText(), password.getPassword());
                         
                        message_label.setForeground(new java.awt.Color(52, 191, 89));
                        clearContent();
                        message_label.setText("Zarejestrowano");                       
                    } else {
                        message_label.setForeground(new java.awt.Color(204, 0, 0));
                        message_label.setText("Użytkownik o podanym adresie email już istnieje");
                    }

                } else {
                    message_label.setForeground(new java.awt.Color(204, 0, 0));
                    message_label.setText("Użytkownik o podanej nazwie już istnieje");
                }

                // if (rejestracja(imie_textF.getText(), Nazwisko_textF.getText(), nr_telefonu_textF.getText(), email_textF.getText(), 
                //     kraj__textF.getText(), kod_pocztowy_textF.getText(), miaso__textF.getText(), ulica_textF.getText(), nr_domu_textF.getText(), 
                //     nr_mieszkania_textF.getText(), login_textF.getText(), haslo_textF.getText()) == true ) {

                //     message_label.setForeground(new java.awt.Color(52, 191, 89));
                //     message_label.setText("Zarejestrowano");
                // } else {
                //     message_label.setForeground(new java.awt.Color(204, 0, 0));
                //     message_label.setText("Użytkownik o podanej nazwie już istnieje");
                // }
            }
        }
    }//GEN-LAST:event_zarejestruj_buttonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ekran_rejestracji.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ekran_rejestracji.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ekran_rejestracji.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ekran_rejestracji.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ekran_rejestracji().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Nazwisko_textF;
    private javax.swing.JTextField email_textF;
    private javax.swing.JTextField imie_textF;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField kod_pocztowy_textF;
    private javax.swing.JTextField kraj__textF;
    private javax.swing.JTextField login_textF;
    private javax.swing.JLabel message_label;
    private javax.swing.JTextField miaso__textF;
    private javax.swing.JTextField nr_domu_textF;
    private javax.swing.JTextField nr_mieszkania_textF;
    private javax.swing.JTextField nr_telefonu_textF;
    private javax.swing.JPasswordField password;
    private javax.swing.JPasswordField password1;
    private javax.swing.JButton powrotButton;
    private javax.swing.JTextField ulica_textF;
    private javax.swing.JButton zarejestruj_button;
    // End of variables declaration//GEN-END:variables
}
