/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Ekrany;

import Dodatkowe.ProjektKlienta;
import Dodatkowe.dodanyProjekt;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Maciek
 */
public class Ekran_szczegolow_zamowienia extends javax.swing.JFrame {
    
    ArrayList<ProjektKlienta> koszyk_proj_klient;
    ArrayList<dodanyProjekt> koszyk;
    EkranKlienta klient;
    
    public void setKoszykProjektuKlienta(ArrayList<ProjektKlienta> k){
        this.koszyk_proj_klient = k;
    }

    public void setKoszyk(ArrayList<dodanyProjekt> k){
        this.koszyk = k;
    }
    
    public void setEkranKlienta(EkranKlienta kl){
        this.klient = kl;
    }

    /**
     * Creates new form Ekran_szczegolow_zamowienia
     */
    public Ekran_szczegolow_zamowienia() {
        initComponents();
        
    }
    
    public void koszykProjektowKlientaDoTabeli() {
        DefaultTableModel model = (DefaultTableModel) tabela_proj_klienta.getModel();

        for (int i = 0; i < koszyk_proj_klient.size(); i++) {
            int id_typ = koszyk_proj_klient.get(i).getIdTypu();
            int id_laczenia = koszyk_proj_klient.get(i).getIdLaczenia();
            String dlugosc = koszyk_proj_klient.get(i).getDlugosc();
            String szerokosc = koszyk_proj_klient.get(i).getSzerokosc();
            String wysokosc = koszyk_proj_klient.get(i).getWysokosc();

            String laczenia;
            String typ;

            switch (id_typ) {
                case 1: typ = "Stół";
                case 2: typ = "Krzesło";
                case 3: typ = "Fotel";
                case 4: typ = "Łóżko";
                case 5: typ = "Sofa";
                case 6: typ = "Buirko";
                case 7: typ = "Szafa";
                case 8: typ = "Komoda";
                case 9: typ = "Szafka nocna";
                case 10: typ = "Narożnik";
                case 11: typ = "Regał";
                case 12: typ = "Kredens";
                default: typ = "brak";
            }

            switch (id_laczenia) {
                case 1: laczenia = "wkręty";
                case 2: laczenia = "klej";
                case 3: laczenia = "wciskowe";
                case 4: laczenia = "kołki";
                case 5: laczenia = "mimośrody";
                case 6: laczenia = "gwintowe";
                default: laczenia = "wkręty";
            }

            Object[] row = {typ, laczenia, dlugosc, szerokosc, wysokosc};
            model.addRow(row);
        }
    }


    public void koszykDoTabeli() {
        DefaultTableModel model = (DefaultTableModel) jTable2.getModel();
        
        for (int i=0; i < koszyk.size(); i++){
            String nr = koszyk.get(i).getId();
            String nazwa = koszyk.get(i).getNazwa();
            String typ = koszyk.get(i).getTyp();
            String cena = koszyk.get(i).getCena();
            //String mat = koszyk.get(i).getMaterial();
            //String opcj = koszyk.get(i).getOpcjonalneCzesci();
            
            Object[] tab = {nr, nazwa, typ, cena};
            
            model.addRow(tab);
        }
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        usunButton = new javax.swing.JButton();
        zlozZamowienieButton = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tabela_proj_klienta = new javax.swing.JTable();
        usunButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        powrotButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setRequestFocusEnabled(false);
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel2.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 340, 30));

        usunButton.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        usunButton.setText("Usuń produkt");
        usunButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usunButtonActionPerformed(evt);
            }
        });
        jPanel2.add(usunButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 460, 150, 50));

        zlozZamowienieButton.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        zlozZamowienieButton.setText("Złóż zamówienie");
        zlozZamowienieButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                zlozZamowienieButtonActionPerformed(evt);
            }
        });
        jPanel2.add(zlozZamowienieButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 530, 170, 50));

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nr", "Mebel", "Ilość", "Cena"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(jTable2);
        if (jTable2.getColumnModel().getColumnCount() > 0) {
            jTable2.getColumnModel().getColumn(0).setResizable(false);
            jTable2.getColumnModel().getColumn(0).setPreferredWidth(20);
            jTable2.getColumnModel().getColumn(1).setResizable(false);
            jTable2.getColumnModel().getColumn(2).setResizable(false);
        }

        jPanel2.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 330, 380));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel3.setText("Zamówienia z Katalogu ");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 360, 40));

        tabela_proj_klienta.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Typ", "Łączenia", "Długość", "Szerokość", "Wysokość"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(tabela_proj_klienta);
        if (tabela_proj_klienta.getColumnModel().getColumnCount() > 0) {
            tabela_proj_klienta.getColumnModel().getColumn(0).setPreferredWidth(20);
        }

        jPanel2.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 70, 380, 380));

        usunButton1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        usunButton1.setText("Usuń produkt");
        usunButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usunButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(usunButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 460, 150, 50));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel2.setText("Własne projekty ");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 10, 270, 40));

        jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel2.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 70, 30, 440));
        jPanel2.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 50, 400, 30));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 780, 590));

        powrotButton.setText("Powrót");
        powrotButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                powrotButtonActionPerformed(evt);
            }
        });
        jPanel1.add(powrotButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 10, 120, 30));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setText("Szczegóły zamówienia z katalogu");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 370, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void usunButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usunButtonActionPerformed

        try{
            DefaultTableModel model = (DefaultTableModel) jTable2.getModel();
            for(int i=1; i<10; i++){
                model.removeRow(0);
            }
        }catch(Exception e){
            e.getStackTrace();
        }
        
        System.out.println(jTable2.getSelectedRow());
        
        koszyk.remove(jTable2.getSelectedRow()+1);
        
        koszykDoTabeli();
    }//GEN-LAST:event_usunButtonActionPerformed

    private void powrotButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_powrotButtonActionPerformed
        klient.setKoszyk(koszyk);
        klient.setKoszykProjektowKlienta(koszyk_proj_klient);
        this.setVisible(false);
    }//GEN-LAST:event_powrotButtonActionPerformed

    private void usunButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usunButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usunButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ekran_szczegolow_zamowienia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ekran_szczegolow_zamowienia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ekran_szczegolow_zamowienia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ekran_szczegolow_zamowienia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ekran_szczegolow_zamowienia().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JButton powrotButton;
    private javax.swing.JTable tabela_proj_klienta;
    private javax.swing.JButton usunButton;
    private javax.swing.JButton usunButton1;
    private javax.swing.JButton zlozZamowienieButton;
    // End of variables declaration//GEN-END:variables
}
